# -*- coding: utf-8 -*-
"""PCD MENEMUKAN PERBEDAAN 2 GAMBAR FIX.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sPndaI2xRtzX72KxYhO87_0v-9rPx_Zl
"""

# impor library yang diperlukan
from matplotlib import pyplot as plt
from skimage.measure import compare_ssim
import imutils
import cv2

from google.colab import drive
drive.mount('/content/drive')

# Load citra dari google drive
imageA = cv2.imread('/content/drive/MyDrive/PCD/gambar awal desain.png')
imageB = cv2.imread('/content/drive/MyDrive/PCD/gambar kedua desain.png')

# Konvert citra asli menjadi keabuan
grayA = cv2.cvtColor(imageA, cv2.COLOR_BGR2GRAY)
grayB = cv2.cvtColor(imageB, cv2.COLOR_BGR2GRAY)

plt.xticks([]), plt.yticks([])
plt.imshow(grayA)
plt.title('gambar awal,- ASLI - Grayscale')
plt.show()

plt.xticks([]), plt.yticks([])
plt.imshow(grayB)
plt.title('gambar kedua,- PERUBAHAN - Grayscale')
plt.show()

# Hitung Structural Similarity Index (SSIM) antara dua citra
# pastikan bahwa perbeddan citra dikembalikan nilainya
(score, diff) = compare_ssim(grayA, grayB, full=True)
diff = (diff * 255).astype("uint8")
print("SSIM: {} Rentang nilai -1 s/d 1 (nilai mendekati 1 berarti 
antar citra hampir sempurna sama)".format(score))

# threshold perbedaan citra, diikuti dengan pencarian kontur
# memperoleh area yang berbeda dari dua input citra
thresh = cv2.threshold(diff, 0, 255,
 cv2.THRESH_BINARY_INV | cv2.THRESH_OTSU)[1]
cnts = cv2.findContours(thresh.copy(), cv2.RETR_EXTERNAL,
 cv2.CHAIN_APPROX_SIMPLE)
cnts = imutils.grab_contours(cnts)

# perulangan pada kontur
for c in cnts:
  # menghitung batas kotak dari kontur dan menggambar
 # batas kotak pada citra input untuk mewakili dua citra yang berbeda
 (x, y, w, h) = cv2.boundingRect(c)
 cv2.rectangle(imageA, (x, y), (x + w, y + h), (0, 0, 255), 2)
 cv2.rectangle(imageB, (x, y), (x + w, y + h), (0, 0, 255), 2)

# tampilkan citra
plt.xticks([]), plt.yticks([])
plt.imshow(cv2.cvtColor(imageA, cv2.COLOR_BGR2RGB))
plt.title('gambar awal,- ASLI')
plt.show()

plt.xticks([]), plt.yticks([])
plt.imshow(cv2.cvtColor(imageB, cv2.COLOR_BGR2RGB))
plt.title('gambar kedua,- PERUBAHAN')
plt.show()

plt.xticks([]), plt.yticks([])
plt.imshow(diff)
plt.title('Perbedaan')
plt.show()

plt.xticks([]), plt.yticks([])
plt.imshow(thresh)
plt.title('Threshold')
plt.show()